name = "Immersive Automation"
author = "Ralph Schuler"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b66206588e7478b9db76297eb5f3733008c67174943ca13af91f0e14fdaa7d6"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
