name = "Immersive Automation"
author = "Ralph Schuler"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7b147e91c18e9025b9234194b8ccaaf51a7999faf563577ab4c2050dc854994"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
