name = "Immersive Automation"
author = "Ralph Schuler"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e21f37604d28c2b851cf1103e4f691cf5cf0ec6172ff0e78f2ea42fea39986a2"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
