name = "Immersive Automation"
author = "Ralph Schuler"
version = "0.1.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e065948b045a20f4b2aba617cbd177299583d00674d84265e26b76a98c2fcac"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
