name = "Immersive Automation"
author = "Ralph Schuler"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df9713bc04948c8a8269bf42133feed5a4b0484375d12ef6eede63ab1d910a72"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
