name = "Immersive Automation"
author = "Ralph Schuler"
version = "0.1.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57fd7c4b33927e0753de6f69eef96dd1713928db535968b3185ce833b6999220"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
