name = "Immersive Automation"
author = "Ralph Schuler"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "026e4f5f0044925b810d0274ec770d8f60452e6f97b41dd52478e12debc47326"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
