name = "Immersive Automation"
author = "Ralph Schuler"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "237729f2d43a500009ad9f0d47524a5b1a30c2aa2e848827bd670b40d6d28049"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
