name = "Immersive Automation"
author = "Ralph Schuler"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa5eef5ce04e2aea9bbd9beef672e88a524e078a32540488ef6eac99572efb3b"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
