name = "Immersive Automation"
author = "Ralph Schuler"
version = "0.1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43140186a9a3df046c3ae5876a542f452d10884e5b49fe0c6ddd8b1be2f4d12f"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
