name = "Immersive Automation"
author = "Ralph Schuler"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "364c9744f842984a59bb21c452eefb25b78808bbb68f86ca2f7cb8e024ffc80c"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
