name = "Immersive Automation"
author = "Ralph Schuler"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "020f6b7a27d43a7680a58165e449987ddfea059ad052c2df0645c6d1c529a95a"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
