name = "Immersive Automation"
author = "Ralph Schuler"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df6819d7ff10c52ed3da8537785e355c7b6f906888921ba874ec114bc94b8ebb"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
