name: Build and Publish

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  MINECRAFT_VERSION: 1.20.1

  MODRINTH_ID: RTIfQdFP
  CURSEFORGE_ID: 1206555

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup pakku
        run: brew install juraj-hrivnak/pakku/pakku

      - name: Build and Export
        run: pakku export

      - name: Publish
        uses: Kira-NT/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-files: |
            build/modrinth/*.mrpack
            build/serverpack/*.zip

          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-files: |
            build/curseforge/*.zip
            build/serverpack/*.zip

          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-files: |
            build/curseforge/*.zip
            build/modrinth/*.mrpack
            build/serverpack/*.zip
