name: Publish on Github, Curseforge, Modrinth

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  MINECRAFT_VERSION: 1.20.1

  MODRINTH_ID: RTIfQdFP
  CURSEFORGE_ID: 1206555

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          brew install-bundler-gems
          brew install juraj-hrivnak/pakku/pakku

      - name: Build Curseforge, Modrinth, Serverpack
        run: |
          pakku export

      - name: Publish Curseforge, Modrinth, Github
        uses: Kira-NT/mc-publish
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-files: |
            build/modrinth/*.mrpack
            build/serverpack/*.zip

          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-files: |
            build/curseforge/*.zip
            build/serverpack/*.zip

          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-files: |
            build/curseforge/*.zip
            build/modrinth/*.mrpack
            build/serverpack/*.zip
